name: Linkedin Marketing Workflow

on:
  schedule:
    # Run every hour
    - cron: '0 6 * * *'
  workflow_dispatch:
jobs:
  linkedin-marketing-workflow:
    name: Does a linked in post using your rss feed
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/linkedin-marketing-workflow@main
        with:
          rss_feed: "https://leosmith.xyz/rss/blog.xml"
          LINKEDIN_SECRET: ${{secrets.LINKEDIN_SECRET}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
